export const GAME = {
    START_BALANCE: 10000,
    MONTHLY_REWARD: 500,
    TRADE_FEE: 0.001,
    DEMAND_DAMPING: 0.1,
    MOMENTUM_DAMPING: 0.2,
    SENTIMENT_DECAY: 0.9,
    SENTIMENT_DAMPING: 0.05,
    WHALE_PROBABILITY: 0.1,
    WHALE_SIZE_MIN: 0.05,
    WHALE_SIZE_MAX: 0.2,
    MIN_FEE: 1.0,
};